name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          # This will not let the issue.title run in the shell
          # It will be treated as a string value in the environment
          TITLE: ${{ github.event.issue.title }}
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi